NetworkXAsyncLPAcommunitiesEmailCore:
  lib: "networkx"
  dataset_path: "storage/email-Eu-core-undirected.txt"
  algorithm: "asyn_lpa_communities"
  gt_path: "storage/email-Eu-core-department-labels.txt"
  gt_is_overlapping: False