## Friendster (undirected, overlapping)
### NetworkX
NetworkXCommunityGirvanNewmanFriendster:
  lib: "networkx"
  dataset_path: "storage/com-friendster.ungraph.txt"
  algorithm: "girvan_newman"
  gt_path: "storage/com-friendster.all.cmty.txt"
  gt_is_overlapping: True

NetworkXAsyncLPAcommunitiesFriendster:
  lib: "networkx"
  dataset_path: "storage/com-friendster.ungraph.txt"
  algorithm: "asyn_lpa_communities"
  gt_path: "storage/com-friendster.all.cmty.txt"
  gt_is_overlapping: True

NetworkXLabelPropagationsFriendster:
  lib: "networkx"
  dataset_path: "storage/com-friendster.ungraph.txt"
  algorithm: "label_propagation_communities"
  gt_path: "storage/com-friendster.all.cmty.txt"
  gt_is_overlapping: True