Benchmark1:
  lib: "snap"
  dataset_path: "storage/0.05-com-dblp.ungraph.txt"
  algorithm: "CNM"

Benchmark2:
  lib: "networkx"
  dataset_path: "another_sample_path/path"
  algorithm: "SBM"

Benchmark3:
  lib: "graphtool"
  dataset_path: "another_data_set_path/path"
  algorithm: "fancy"