Benchmark1:
  lib: "snap"
  dataset_path: "storage/0.05-com-dblp.ungraph.txt"
  algorithm: "CNM"

#Benchmark2:
#  lib: "networkx"
#  dataset_path: "storage/0.05-com-dblp.ungraph.txt"
#  algorithm: "k_clique_communities"
#
#Benchmark3:
#  lib: "graphtool"
#  dataset_path: "storage/0.05-com-dblp.ungraph.txt"
#  algorithm: "mcmc_anneal"